class ModeException(Exception):
    def __init__(self, message: str): ...

class SizeException(Exception):
    def __init__(self, message: str): ...

class PaddingException(Exception):
    def __init__(self, message: str): ...

class ReshapingException(Exception):
    def __init__(self, message: str): ...

class ShapeMismatch(Exception):
    def __init__(self, message: str): ...
