from typing import Dict

import torch

from nemesys.modelling.analysers.analyser import Analyser

class PyTorchAnalyser(Analyser, torch.nn.Module):
    def __init__(self, module: torch.nn.Module): ...
    @property
    def module(self) -> torch.nn.Module: ...
    def analyse(self, inputs: torch.Tensor) -> Dict[str, Dict[str, torch.Tensor]]: ...
    def forward(self, inputs: torch.Tensor) -> Dict[str, Dict[str, torch.Tensor]]: ...
