from typing import Iterable, List

from nemesys.modelling.blocks.block import Block
from nemesys.modelling.stores.store import Store

class ListStore(Store):
    def __init__(self): ...
    @property
    def blocks(self) -> List[Block]: ...
    def append(self, content: Block): ...
    def get_all(self) -> Iterable[Block]: ...
    def get_one(self, key: int) -> Block: ...
    def get_some(self, keys: Iterable[int]) -> Iterable[Block]: ...
    def remove_all(self): ...
    def remove_one(self, key: int): ...
    def remove_some(self, keys: Iterable[int]): ...
    def set_all(self, content: Iterable[Block]): ...
    def set_one(self, key: int, content: Block): ...
    def set_some(self, keys: Iterable[int], contents: Iterable[Block]): ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
