from typing import Dict

import torch

from nemesys.modelling.encoders.encoder import Encoder

class PyTorchEncoder(torch.nn.Module, Encoder):
    def __init__(self, module: torch.nn.Module): ...
    @property
    def module(self) -> torch.nn.Module: ...
    def encode(self, inputs: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]: ...
    def forward(self, inputs: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]: ...
